### PR TITLE
[sharktank] Unpin NumPy

### PR DESCRIPTION
**Pull request by marbre**
`numpy<2.0` is required for Windows with `torch<2.4`. Expanding testing on Windows with Python 3.12 and torch 2.4.1.

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
Discussed some of the test failures offline. Some of the "Data-dependent Tests" failures will be fixed along with https://github.com/ggerganov/llama.cpp/issues/10127. Not sure about the Windows test failures.

**Comment by marbre** [comment]
> Discussed some of the test failures offline. Some of the "Data-dependent Tests" failures will be fixed along with [ggerganov/llama.cpp#10127](https://github.com/ggerganov/llama.cpp/issues/10127). Not sure about the Windows test failures.

The "Data-dependent Tests" are indeed fixed with the gguf version 0.1.13 release. At the moment we only specify a minimum version (`gguf>=0.11.0`) and it would be fine to leave this as is.

**Comment by marbre** [comment]
Moving all changes unrelated to unpinning NumPy to #697.

**Comment by marbre** [comment]
> > Discussed some of the test failures offline. Some of the "Data-dependent Tests" failures will be fixed along with [ggerganov/llama.cpp#10127](https://github.com/ggerganov/llama.cpp/issues/10127). Not sure about the Windows test failures.
> 
> The "Data-dependent Tests" are indeed fixed with the gguf version 0.1.13 release. At the moment we only specify a minimum version (`gguf>=0.11.0`) and it would be fine to leave this as is.

@ScottTodd you're okay with not raising the minimum version of gguf?

**Comment by ScottTodd** [comment]
> > > Discussed some of the test failures offline. Some of the "Data-dependent Tests" failures will be fixed along with [ggerganov/llama.cpp#10127](https://github.com/ggerganov/llama.cpp/issues/10127). Not sure about the Windows test failures.
> > 
> > 
> > The "Data-dependent Tests" are indeed fixed with the gguf version 0.1.13 release. At the moment we only specify a minimum version (`gguf>=0.11.0`) and it would be fine to leave this as is.
> 
> @ScottTodd you're okay with not raising the minimum version of gguf?

Yeah, though I don't see much harm in updating that minimum also.

**Pull request merged**
